### ISSUE TITLE
运行educhat_gradio.py报错

### ISSUE THREAD

**Issue by luchenwei9266** [icalk-nlp/EduChat#1]
`transformers`、`pytorch`、`gradio` 均已成功安装

运行这个命令时 `python educhat_gradio.py` 报了如下错误

`(educhat) [root@VM-0-2-tencentos demo]# python educhat_gradio.py`
`Traceback (most recent call last):
  File "educhat_gradio.py", line 7, in <module>
    from model_training.custom_datasets.formatting import QA_SPECIAL_TOKENS, format_pairs, format_system_prefix
ModuleNotFoundError: No module named 'model_training'
`
好像有些模块没装上，请问能告诉是哪个包吗？搜索了一下好像没找正确的模块

**Comment by butyuhao** [comment]
我们已经移除了对于model_training的依赖。请使用最新的educhat_gradio.py，并参考：https://github.com/icalk-nlp/EduChat#%E7%BD%91%E9%A1%B5demo
